pjt_05/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

pjt_05/trends/urls.py
from django.urls import path
from . import views

app_name = 'trends'
urlpatterns = [
    path('keyword/', views.keyword, name = 'keyword'),
    path('keyword/<int:pk>/', views.keyword_detail, name = 'keyword_detail'),
    path('crawling/', views.crawling, name = 'crawling'),
    path('crawling/histogram', views.crawling_histogram, name = 'crawling_histogram'),
    path('crawling/advanced', views.crawling_advanced, name = 'crawling_advanced'),
]

pjt_05/trends/models.py
from django.db import models



class Keyword(models.Model):
    pass

class Trend(models.Model):
    pass

pjt_05/trends/views.py
from django.shortcuts import render


# 키워드 저장 및 keyword.html 렌더링
def keyword(request):
    return render(request, 'trends/keyword.html')

# 키워드 삭제 및 keyword.html로 리다이렉션
def keyword_detail():
    pass

# 크롤링 수행 및 결과 개수 출력
def crawling():
    pass

# 크롤링 수행 및 결과 개수 막대 그래프로 출력
def crawling_histogram():
    pass

# 지난 1년을 기준으로
# 크롤링 수행 및 결과 개수 막대 그래프 출력
def crawling_advanced():
    pass

pjt_05/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>트렌드 분석 애플리케이션</h1>
    <a href="{% url "trends:keyword" %}">키워드 추가</a> |
    <a href="{% url "trends:crawling" %}">크롤링</a> |
    <a href="{% url "trends:crawling_histogram" %}">히스토그램</a> |
    <a href="{% url "trends:crawling_advanced" %}">지난 1년 크롤링</a> |
    {% block content %}{% endblock content %}
</body>
</html>