pjt_06/boards/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/update/', views.update, name='update'),
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>', views.comment_detail, name='comment_detail'),
]

pjt_06/boards/models.py
from django.db import models
from django.conf import settings

class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pjt_06/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content',)

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('content',)

pjt_06/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required


@require_http_methods(['GET'])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards' : boards
    }
    return render(request, 'boards/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form' : form,
    }   
    return render(request, 'boards/create.html', context)
    
    
@require_http_methods(['GET', 'POST'])
def detail(request, board_pk):
    board = get_object_or_404(Board,pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board':board,
        'comments':comments,
        'comment_form':comment_form,
    }
    return render(request, 'boards/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)
    context = {
        'board':board,
        'form':form,
    }
    return render(request, 'boards/update.html', context)


@require_http_methods(['POST'])
def comment(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('boards:detail', board.pk)
        

@require_http_methods(['POST'])
def comment_detail(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)

pjt_06/boards/templates/boards/create.html
{% extends "base.html" %}

{% block content %}
<div>
    <h1 class="mb-4">생성 페이지</h1>
    <form action="{% url 'boards:create' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-light">생성하기</button>
    </form>
</div>
{% endblock content %}

pjt_06/boards/templates/boards/detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="d-flex justify-content-between">
        <h1 class="mb-4">상세 페이지</h1>
    </div>
    <p>글번호 : {{board.pk}}</p>
    <p>작성자 : {{board.author}}</p>
    <p>글제목 : {{board.title}}</p>
    <p>글내용 : {{board.content}}</p>
    <p>작성날짜 : {{board.created_at}}</p>
    <p>수정날짜 : {{board.updated_at}}</p>
    <hr>
    <div class="mb-5 d-flex justify-content-between">
        <a href="{% url 'boards:index' %}"><button class="btn btn-light">메인 페이지로</button></a>
        <div class="d-flex">
            <a href="{% url "boards:update" board.id%}">수정하기</a>
            <form action="{% url "boards:detail" board.id%}" method='POST'>
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">삭제하기</button>
            </form>
        </div>
    <form action="{% url "boards:comment" board.id %}" method='POST'>
        {% csrf_token %}
        <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
        {{comment_form.as_p}}
    </form>

    <div class="mt-5">
        {% if comments|length == 0 %}
        댓글이 없습니다.
        {% else %}
            {% for comment in comments %}
            <div class="my-3 d-flex justify-content-between">
                <div>
                    <span>{{ comment.content }}</span>
                    <span class="mx-5">({{ comment.created_at }})</span>
                  </div>
                    <div>
                      <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
                        {% csrf_token %}
                        <button class="btn btn-light">삭제하기</button>
                      </form>
                    </div>
                  </div>
                  <hr/>                    
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

pjt_06/boards/templates/boards/index.html
{% extends "base.html" %}

{% block content %}
<div>
    <div class="d-flex justify-content-between">
      <h1 class="mb-4">메인 페이지</h1>
      <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
    </div>
    {% if boards|length == 0 %}
    아직 게시글이 없습니다
    {% else %}
    {% for board in boards %}
        글번호 : {{board.pk}}
        <br>
        작성자 : <a href="{% url "accounts:follow" user.pk %}">{{board.author}}</a>
        <br>
        글제목 : <a href="{% url "boards:detail" board.pk %}">{{board.title}}</a>
        <hr>
    {% endfor %}
    {% endif %}
</div>
{% endblock content %}

pjt_06/boards/templates/boards/update.html
{% extends "base.html" %}

{% block content %}
<div>
    <h1 class="mb-4">수정 페이지</h1>
    <form action="{% url 'boards:update' board.id%}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="수정하기">
    </form>
</div>
{% endblock content %}